# VARIABLES
# ---------
title: qunlix
rss-title: "qunlix's Blog"
copyright: "Copyright 2012, qunlix"
githuburl: "https://github.com/qunlix/qunlix.com"


# JEKYLL
# ------
pygments: true
permalink: /:title/
paginate: 5
exclude: ['Makefile', 'README.md', 'psd']


# PLUGINS
# -------
lessc: lessc --yui-compress
